name: Release

env:
  GH_TOKEN: ${{ secrets.PAT }}

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npx ci
    # - name: Install semantic-release extra plugins
    #   run: npm install --save-dev @semantic-release/changelog @semantic-release/git
    - name: Release
      run: npx semantic-release